sonar.organization=kyuri-metro
sonar.projectKey=kyuri-metro_njmetro-railmap-creator
sonar.projectName=njmetro-railmap-creator

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/builtin*LineStations.ts,**/*.d.ts,**/vite-env.d.ts
sonar.coverage.exclusions=**/*.test.ts,**/builtin*LineStations.ts,**/*.d.ts,**/main.tsx,**/vite-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
