/**
 * 简办动态演示线网内置站点。有不确定性；请以官方最终公布为准。
 * 详见 docs/builtin-jianban-attribution.md（BV1Bw41127DF）。
 */
import { resolveJianbanLineBackgroundColor, resolveJianbanLineForegroundColor } from './jianbanLineColors';
import type { StationItem } from './features/generatorSlice';

type SupportedLineId = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | '10' | '11' | '16' | '18' | 'S1' | 'S2' | 'S3' | 'S4' | 'S5' | 'S6' | 'S7' | 'S8' | 'S9';
type BuiltinStationSeed = { chName: string; enName: string };

const builtinStationSeedsByLineId: Record<SupportedLineId, BuiltinStationSeed[]> = {
  '1': [
    { chName: '八卦洲大桥南', enName: 'Baguazhoudaqiaonan' },
    { chName: '笆斗山', enName: 'Badoushan' },
    { chName: '燕子矶', enName: 'Yanziji' },
    { chName: '吉祥庵', enName: 'Jixiangan' },
    { chName: '晓庄', enName: 'Xiaozhuang' },
    { chName: '迈皋桥', enName: 'Maigaoqiao' },
    { chName: '红山动物园', enName: 'Hongshan Zoo' },
    { chName: '南京站', enName: 'Nanjing Railway Station' },
    { chName: '新模范马路', enName: 'Xinmofanmalu' },
    { chName: '玄武门', enName: 'Xuanwumen' },
    { chName: '鼓楼', enName: 'Gulou' },
    { chName: '珠江路', enName: 'Zhujianglu' },
    { chName: '新街口', enName: 'Xinjiekou' },
    { chName: '张府园', enName: 'Zhangfuyuan' },
    { chName: '三山街', enName: 'Sanshanjie' },
    { chName: '中华门', enName: 'Zhonghuamen' },
    { chName: '安德门', enName: 'Andemen' },
    { chName: '天隆寺', enName: 'Tianlongsi' },
    { chName: '软件大道', enName: 'Ruanjiandadao' },
    { chName: '花神庙', enName: 'Huashenmiao' },
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '双龙大道', enName: 'Shuanglongdadao' },
    { chName: '河定桥', enName: 'Hedingqiao' },
    { chName: '胜太路', enName: 'Shengtailu' },
    { chName: '百家湖', enName: 'Baijiahu' },
    { chName: '小龙湾', enName: 'Xiaolongwan' },
    { chName: '竹山路', enName: 'Zhushanlu' },
    { chName: '天印大道', enName: 'Tianyindadao' },
    { chName: '龙眠大道', enName: 'Longmiandadao' },
    { chName: '南医大·江苏经贸学院', enName: 'NMU/JIETT' },
    { chName: '南京交院', enName: 'NJCI' },
    { chName: '中国药科大学', enName: 'CPU' },
  ],
  '2': [
    { chName: '仙林湖', enName: 'Xianlinhu' },
    { chName: '经天路', enName: 'Jingtianlu' },
    { chName: '南大仙林校区', enName: 'NJU Xianlin Campus' },
    { chName: '羊山公园', enName: 'Yangshangongyuan' },
    { chName: '仙林中心', enName: 'Xianlinzhongxin' },
    { chName: '学则路', enName: 'Xuezelu' },
    { chName: '仙鹤门', enName: 'Xianhemen' },
    { chName: '金马路', enName: 'Jinmalu' },
    { chName: '马群', enName: 'Maqun' },
    { chName: '钟灵街', enName: 'Zhonglingjie' },
    { chName: '孝陵卫', enName: 'Xiaolingwei' },
    { chName: '下马坊', enName: 'Xiamaofang' },
    { chName: '苜蓿园', enName: 'Muxuyuan' },
    { chName: '明故宫', enName: 'Minggugong' },
    { chName: '西安门', enName: 'Xi\'anmen' },
    { chName: '大行宫', enName: 'Daxinggong' },
    { chName: '新街口', enName: 'Xinjiekou' },
    { chName: '上海路', enName: 'Shanghailu' },
    { chName: '汉中门', enName: 'Hanzhongmen' },
    { chName: '莫愁湖', enName: 'Mochouhu' },
    { chName: '云锦路', enName: 'Yunjinlu' },
    { chName: '集庆门大街', enName: 'Jiqingmendajie' },
    { chName: '兴隆大街', enName: 'Xinglongdajie' },
    { chName: '奥体东', enName: 'Olympic Stadium East' },
    { chName: '元通', enName: 'Yuantong' },
    { chName: '雨润大街', enName: 'Yurundajie' },
    { chName: '油坊桥', enName: 'Youfangqiao' },
    { chName: '螺塘路', enName: 'Luotanglu' },
    { chName: '青莲街', enName: 'Qinglianjie' },
    { chName: '天保街', enName: 'Tianbaojie' },
    { chName: '鱼嘴', enName: 'Yuzui' },
  ],
  '3': [
    { chName: '琥珀泉', enName: 'Hupoquan' },
    { chName: '花旗营', enName: 'Huaqiying' },
    { chName: '南京北站', enName: 'Nanjingbei Railway Station' },
    { chName: '林场', enName: 'Linchang' },
    { chName: '星火路', enName: 'Xinghuolu' },
    { chName: '东大成贤学院', enName: 'SEU Chengxian College' },
    { chName: '泰冯路', enName: 'Taifenglu' },
    { chName: '天润城', enName: 'Tianruncheng' },
    { chName: '柳洲东路', enName: 'Liuzhoudonglu' },
    { chName: '上元门', enName: 'Shangyuanmen' },
    { chName: '五塘广场', enName: 'Wutangguangchang' },
    { chName: '小市', enName: 'Xiaoshi' },
    { chName: '南京站', enName: 'Nanjing Railway Station' },
    { chName: '南京林业大学·新庄', enName: 'NFU/Xinzhuang' },
    { chName: '鸡鸣寺', enName: 'Jimingsi' },
    { chName: '浮桥', enName: 'Fuqiao' },
    { chName: '大行宫', enName: 'Daxinggong' },
    { chName: '常府街', enName: 'Changfujie' },
    { chName: '夫子庙', enName: 'Fuzimiao' },
    { chName: '武定门', enName: 'Wudingmen' },
    { chName: '雨花门', enName: 'Yuhuamen' },
    { chName: '卡子门', enName: 'Kazimen' },
    { chName: '大明路', enName: 'Daminglu' },
    { chName: '明发广场', enName: 'Mingfaguangchang' },
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '宏运大道', enName: 'Hongyundadao' },
    { chName: '胜太西路', enName: 'Shengtaixilu' },
    { chName: '天元西路', enName: 'Tianyuanxilu' },
    { chName: '九龙湖', enName: 'Jiulonghu' },
    { chName: '诚信大道', enName: 'Chengxindadao' },
    { chName: '东大九龙湖校区', enName: 'SEU Jiulonghu Campus' },
    { chName: '秣周东路', enName: 'Mozhoudonglu' },
    { chName: '上秦淮西', enName: 'Shangqinhuaixi' },
    { chName: '秣陵', enName: 'Moling' },
  ],
  '4': [
    { chName: '华侨城东', enName: 'Huachengdong' },
    { chName: '欢乐谷', enName: 'Happy Valley' },
    { chName: '官窑山', enName: 'Guanyaoshan' },
    { chName: '白象', enName: 'Baixiang' },
    { chName: '仙林湖', enName: 'Xianlinhu' },
    { chName: '西岗桦墅', enName: 'Xiganghuashu' },
    { chName: '孟北', enName: 'Mengbei' },
    { chName: '东流', enName: 'Dongliu' },
    { chName: '灵山', enName: 'Lingshan' },
    { chName: '汇通路', enName: 'Huitonglu' },
    { chName: '金马路', enName: 'Jinmalu' },
    { chName: '徐庄', enName: 'Xuzhuang' },
    { chName: '聚宝山', enName: 'Jubaoshan' },
    { chName: '王家湾', enName: 'Wangjiawan' },
    { chName: '蒋王庙', enName: 'Jiangwangmiao' },
    { chName: '岗子村', enName: 'Gangzicun' },
    { chName: '九华山', enName: 'Jiuhuashan' },
    { chName: '鸡鸣寺', enName: 'Jimingsi' },
    { chName: '鼓楼', enName: 'Gulou' },
    { chName: '云南路', enName: 'Yunnanlu' },
    { chName: '草场门', enName: 'Caochangmen' },
    { chName: '龙江', enName: 'Longjiang' },
    { chName: '江心洲尾', enName: 'Jiangxinzhouwei' },
    { chName: '江北市民中心', enName: 'Jiangbeishiminzhongxin' },
    { chName: '江北商务区', enName: 'Jiangbeishangwuqu' },
    { chName: '定山大街', enName: 'Dingshandajie' },
    { chName: '石佛寺', enName: 'Shifosi' },
    { chName: '瑞龙郊野公园', enName: 'Ruilongjiaoyegongyuan' },
    { chName: '珍珠泉东', enName: 'Zhenzhuanquandong' },
    { chName: '龙之谷', enName: 'Longzhigu' },
    { chName: '护国村', enName: 'Huguocun' },
    { chName: '南京北站', enName: 'Nanjingbei Railway Station' },
    { chName: '余家营', enName: 'Yujiaying' },
  ],
  '5': [
    { chName: '方家营', enName: 'Fangjiaying' },
    { chName: '南京西站', enName: 'Nanjingxi Railway Station' },
    { chName: '静海寺', enName: 'Jinghaisi' },
    { chName: '下关', enName: 'Xiaguan' },
    { chName: '盐仓桥', enName: 'Yancangqiao' },
    { chName: '福建路', enName: 'Fujianlu' },
    { chName: '虹桥', enName: 'Hongqiao' },
    { chName: '青春广场', enName: 'Qingchunguangchang' },
    { chName: '云南路', enName: 'Yunnanlu' },
    { chName: '五台山', enName: 'Wutaishan' },
    { chName: '上海路', enName: 'Shanghailu' },
    { chName: '朝天宫', enName: 'Chaotiangong' },
    { chName: '三山街', enName: 'Sanshanjie' },
    { chName: '夫子庙', enName: 'Fuzimiao' },
    { chName: '通济门', enName: 'Tongjimen' },
    { chName: '光华门', enName: 'Guanghuamen' },
    { chName: '石门坎', enName: 'Shimenkan' },
    { chName: '七桥瓮', enName: 'Qiqiaoweng' },
    { chName: '大校场', enName: 'Dajiaochang' },
    { chName: '神机营', enName: 'Shenjiying' },
    { chName: '东山香樟园', enName: 'Dongshanxiangzhangyuan' },
    { chName: '文靖路', enName: 'Wenjinglu' },
    { chName: '东山', enName: 'Dongshan' },
    { chName: '新亭路', enName: 'Xintinglu' },
    { chName: '竹山路', enName: 'Zhushanlu' },
    { chName: '科宁路', enName: 'Keninglu' },
    { chName: '前庄', enName: 'Qianzhuang' },
    { chName: '诚信大道', enName: 'Chengxindadao' },
    { chName: '九龙湖南', enName: 'Jiulonghunan' },
    { chName: '吉印大道', enName: 'Jiyindadao' },
  ],
  '6': [
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '夹岗', enName: 'Jiagang' },
    { chName: '机场跑道旧址', enName: 'Jichangpaodaojiuzhi' },
    { chName: '市中医院', enName: 'Nanjing Hospital of C.M.' },
    { chName: '应天东街', enName: 'Yingtiandongjie' },
    { chName: '中和桥', enName: 'Zhongheqiao' },
    { chName: '光华门', enName: 'Guanghuamen' },
    { chName: '明故宫', enName: 'Minggugong' },
    { chName: '富贵山', enName: 'Fuguishan' },
    { chName: '岗子村', enName: 'Gangzicun' },
    { chName: '花园路', enName: 'Huayuanlu' },
    { chName: '红山新城', enName: 'Hongshanxincheng' },
    { chName: '营苑南路', enName: 'Yingyuannanlu' },
    { chName: '万寿', enName: 'Wanshou' },
    { chName: '燕江新城', enName: 'Yanjiangxincheng' },
    { chName: '兴学路', enName: 'Xingxuelu' },
    { chName: '兴智街', enName: 'Xingzhijie' },
    { chName: '十月广场', enName: 'Shiyueguangchang' },
    { chName: '金陵石化', enName: 'Jinlingshihua' },
    { chName: '栖霞山', enName: 'Qixiashan' },
  ],
  '7': [
    { chName: '西善桥', enName: 'Xishanqiao' },
    { chName: '螺塘路', enName: 'Luotanglu' },
    { chName: '太清路', enName: 'Taiqinglu' },
    { chName: '永初路', enName: 'Yongchulu' },
    { chName: '嘉陵江东街', enName: 'Jialingjiangdongjie' },
    { chName: '中胜', enName: 'Zhongsheng' },
    { chName: '新城科技园', enName: 'Xinchengkejiyuan' },
    { chName: '梦都大街东', enName: 'Mengdudajiedong' },
    { chName: '应天大街', enName: 'Yingtiandajie' },
    { chName: '南湖', enName: 'Nanhu' },
    { chName: '大士茶亭', enName: 'Dashichating' },
    { chName: '莫愁湖', enName: 'Mochouhu' },
    { chName: '清凉山', enName: 'Qingliangshan' },
    { chName: '草场门', enName: 'Caochangmen' },
    { chName: '古平岗', enName: 'Gupinggang' },
    { chName: '福建路', enName: 'Fujianlu' },
    { chName: '钟阜路', enName: 'Zhongfulu' },
    { chName: '幕府西路', enName: 'Mufuxilu' },
    { chName: '五塘广场', enName: 'Wutangguangchang' },
    { chName: '幕府山', enName: 'Mufushan' },
    { chName: '晓庄', enName: 'Xiaozhuang' },
    { chName: '万寿', enName: 'Wanshou' },
    { chName: '丁家庄', enName: 'Dingjiazhuang' },
    { chName: '丁家庄南', enName: 'Dingjiazhuangnan' },
    { chName: '尧化新村', enName: 'Yaohuaxincun' },
    { chName: '尧化门', enName: 'Yaohuamen' },
    { chName: '仙新路', enName: 'Xianxinlu' },
  ],
  '8': [
    { chName: '十月广场', enName: 'Shiyueguangchang' },
    { chName: '仙新路', enName: 'Xianxinlu' },
    { chName: '仙林站', enName: 'Xianlin Railway Station' },
    { chName: '文澜路', enName: 'Wenlanlu' },
    { chName: '仙林中心', enName: 'Xianlinzhongxin' },
    { chName: '灵山', enName: 'Lingshan' },
    { chName: '麒麟门', enName: 'Qilinmen' },
    { chName: '芝嘉路', enName: 'Zhijialu' },
    { chName: '定林', enName: 'Dinglin' },
    { chName: '智汇路', enName: 'Zhihuilu' },
    { chName: '生态公园', enName: 'Shengtaigongyuan' },
  ],
  '9': [
    { chName: '刘村', enName: 'Liucun' },
    { chName: '足球小镇', enName: 'Zuqiuxiaozhen' },
    { chName: '鱼嘴', enName: 'Yuzui' },
    { chName: '保双街', enName: 'Baoshuangjie' },
    { chName: '江桥路', enName: 'Jiangqiaolu' },
    { chName: '淮河路', enName: 'Huaihelu' },
    { chName: '黄河路', enName: 'Huanghelu' },
    { chName: '青奥公园', enName: 'Qing\'aogongyuan' },
    { chName: '棉花堤', enName: 'Mianhuadi' },
    { chName: '江苏大剧院·宪法公园', enName: 'JSCPA/XIANFAGONGYUAN' },
    { chName: '绿博园', enName: 'Lüboyuan' },
    { chName: '上新河', enName: 'Shangxinhe' },
    { chName: '清江南路', enName: 'Qingjiangnanlu' },
    { chName: '江东门', enName: 'Jiangdongmen' },
    { chName: '管子桥', enName: 'Guanziqiao' },
    { chName: '龙江', enName: 'Longjiang' },
    { chName: '三汊河', enName: 'Sanchahe' },
    { chName: '白云寺', enName: 'Baiyunsi' },
    { chName: '下关', enName: 'Xiaguan' },
    { chName: '四平路广场', enName: 'Sipingluguangchang' },
    { chName: '钟阜路', enName: 'Zhongfulu' },
    { chName: '中央门', enName: 'Zhongyangmen' },
    { chName: '南京站', enName: 'Nanjing Railway Station' },
    { chName: '红山路', enName: 'Hongshanlu' },
    { chName: '红山新城', enName: 'Hongshanxincheng' },
  ],
  '10': [
    { chName: '科工园', enName: 'Kegongyuan' },
    { chName: '科工园东', enName: 'Kegongyuandong' },
    { chName: '雨山路', enName: 'Yushanlu' },
    { chName: '文德路', enName: 'Wendelu' },
    { chName: '龙华路', enName: 'Longhualu' },
    { chName: '南京工业大学', enName: 'Nanjing Tech' },
    { chName: '浦口万汇城', enName: 'Pukouwanhuicheng' },
    { chName: '临江·青奥体育公园', enName: 'Linjiang/YOGSP' },
    { chName: '江心洲', enName: 'Jiangxinzhou' },
    { chName: '绿博园', enName: 'Lüboyuan' },
    { chName: '梦都大街', enName: 'Mengdudajie' },
    { chName: '奥体中心', enName: 'Olympic Stadium' },
    { chName: '元通', enName: 'Yuantong' },
    { chName: '中胜', enName: 'Zhongsheng' },
    { chName: '小行', enName: 'Xiaoxing' },
    { chName: '安德门', enName: 'Andemen' },
    { chName: '共青团路', enName: 'Gongqingtuanlu' },
    { chName: '雨花台', enName: 'Yuhuatai' },
    { chName: '卡子门', enName: 'Kazimen' },
    { chName: '机场跑道旧址', enName: 'Jichangpaodaojiuzhi' },
    { chName: '大校场', enName: 'Dajiaochang' },
    { chName: '承天大道', enName: 'Chengtiandadao' },
    { chName: '高桥门', enName: 'Gaoqiaomen' },
    { chName: '杨庄', enName: 'Yangzhuang' },
    { chName: '石杨路', enName: 'Shiyanglu' },
    { chName: '东麒路', enName: 'Dongqilu' },
  ],
  '11': [
    { chName: '浦洲路', enName:	'Puzhoulu' },
    { chName: '柳洲东路', enName:	'Liuzhoudonglu' },
    { chName: '明滨路', enName:	'Mingbinlu' },
    { chName: '长江大桥北', enName:	'Changjiangdaqiaobei' },
    { chName: '柳洲南路', enName:	'Liuzhounanlu' },
    { chName: '浦东路', enName:	'Pudonglu' },
    { chName: '新马路', enName:	'Xinmalu' },
    { chName: '南京铁道学院', enName: 'NIRT' },
    { chName: '广西梗大街', enName:	'Guangxiangengdajie' },
    { chName: '江北商务区', enName: 'Jiangbeishangwuqu' },
    { chName: '七里河', enName: 'Qilihe' },
    { chName: '临滁街', enName: 'Linchujie' },
    { chName: '浦口万汇城', enName: 'Pukouwanhuicheng' },
    { chName: '城南河', enName: 'Chengnanhe' },
    { chName: '江淼路', enName: 'Jiangmiaolu' },
    { chName: '卓越路', enName: 'Zhuoyuelu' },
    { chName: '行知路', enName: 'Xingzhilu' },
    { chName: '绿水湾路', enName: 'Lvshuiwanlu' },
    { chName: '西江口', enName: 'Xijiangkou' },
    { chName: '马骡圩', enName: 'Maluowei' },
  ],
  '16': [
    { chName: '板桥南', enName: 'Banqiaonan' },
    { chName: '绿洲', enName: 'Lüzhou' },
    { chName: '板桥东', enName: 'Banqiaodong' },
    { chName: '新亭大街', enName: 'Xintingdajie' },
    { chName: '新城大街', enName: 'Xinchengdajie' },
    { chName: '华兴大街', enName: 'Huaxingdajie' },
    { chName: '西善花苑', enName: 'Xishanhuayuan' },
    { chName: '梅欣路', enName: 'Meixinlu' },
    { chName: '梅苑南路', enName: 'Meiyuananlu' },
    { chName: '大定坊', enName: 'Dadingfang' },
    { chName: '银杏山庄', enName: 'Yinxingshanzhuang' },
    { chName: '铁心桥', enName: 'Tiexinqiao' },
    { chName: '软件大道', enName: 'Ruanjiandadao' },
    { chName: '玉兰路', enName: 'Yulanlu' },
    { chName: '大明路', enName: 'Daminglu' },
    { chName: '机场跑道旧址', enName: 'Jichangpaodaojiuzhi' },
  ],
  '18': [
    { chName: '北斗产业园', enName: 'Beidouchanyeyuan' },
    { chName: '南京北站', enName: 'Nanjingbei Railway Station' },
    { chName: '南京铁道学院', enName: 'NIRT' },
    { chName: '新华街', enName: 'Xinhuajie' },
    { chName: '古平岗', enName: 'Gupinggang' },
    { chName: '鼓楼', enName: 'Gulou' },
    { chName: '新街口', enName: 'Xinjiekou' },
    { chName: '中华门', enName: 'Zhonghuamen' },
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '河海大学·佛城西路', enName: 'HHU/Fochengxilu' },
    { chName: '禄口新城东', enName: 'Lukouxinchengdong' },
    { chName: '翔宇路南', enName: 'Xiangyulunan' },
    { chName: '禄口机场3号航站楼', enName: 'T3 of Lukou International Airport' },
    { chName: '禄口机场', enName: 'Lukou International Airport' },
  ],
  'S1': [
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '翠屏山', enName: 'Cuipingshan' },
    { chName: '河海大学·佛城西路', enName: 'HHU/Fochengxilu' },
    { chName: '吉印大道', enName: 'Jiyindadao' },
    { chName: '正方中路', enName: 'Zhengfangzhonglu' },
    { chName: '翔宇路北', enName: 'Xiangyulubei' },
    { chName: '翔宇路南', enName: 'Xiangyulunan' },
    { chName: '禄口机场', enName: 'Lukou International Airport' },
    { chName: '空港新城江宁', enName: 'Konggangxinchengjiangning' },
  ],
  'S2': [
    { chName: '太白', enName: 'Taibai' },
    { chName: '姑孰', enName: 'Gushu' },
    { chName: '马鞍山经开区', enName: 'Ma\'anshanjingkaiqu' },
    { chName: '阳湖', enName: 'Yanghu' },
    { chName: '雨山东路', enName: 'Yushandonglu' },
    { chName: '湖南路·安工大', enName: 'Hunanlu/angongda' },
    { chName: '湖北路·二中', enName: 'Hubeilu/erzhong' },
    { chName: '慈湖高新区', enName: 'Cihugaoxinqu' },
    { chName: '铜井', enName: 'Tongjing' },
    { chName: '牧龙', enName: 'Mulong' },
    { chName: '江宁滨江开发区', enName: 'Jiangning Binjiang Development Zone' },
    { chName: '江宁镇', enName: 'Jiangningzhen' },
    { chName: '板桥南', enName: 'Banqiaonan' },
    { chName: '板桥', enName: 'Banqiao' },
    { chName: '雨花经济开发区', enName: 'Yuhua Jingji Development Zone' },
    { chName: '西善桥', enName: 'Xishanqiao' },
  ],
  'S3': [
    { chName: '仙林站', enName: 'Xianlin Railway Station' },
    { chName: '江苏广电', enName: 'JSBC' },
    { chName: '南大仙林校区', enName: 'NJU Xianlin Campus' },
    { chName: '三阳路', enName: 'Sanyanglu' },
    { chName: '东流', enName: 'Dongliu' },
    { chName: '东郊小镇', enName: 'Dongjiaoxiaozhen' },
    { chName: '中科院', enName: 'UCASNJ' },
    { chName: '泉水路', enName: 'Quanshuilu' },
    { chName: '生态公园', enName: 'Shengtaigongyuan' },
    { chName: '石杨路', enName: 'Shiyanglu' },
    { chName: '上坊工业园', enName: 'Shangfanggongyeyuan' },
    { chName: '湖西路', enName: 'Huxilu' },
    { chName: '东山香樟园', enName: 'Dongshanxiangzhangyuan' },
    { chName: '金盛路', enName: 'Jinshenglu' },
    { chName: '南京南站', enName: 'Nanjingnan Railway Station' },
    { chName: '景明佳园', enName: 'Jingmingjiayuan' },
    { chName: '铁心桥', enName: 'Tiexinqiao' },
    { chName: '春江路', enName: 'Chunjianglu' },
    { chName: '贾西', enName: 'Jiaxi' },
    { chName: '油坊桥', enName: 'Youfangqiao' },
    { chName: '永初路', enName: 'Yongchulu' },
    { chName: '平良大街', enName: 'Pingliangdajie' },
    { chName: '吴侯街', enName: 'Wuhoujie' },
    { chName: '高庙路', enName: 'Gaomiaolu' },
    { chName: '天保', enName: 'Tianbao' },
    { chName: '刘村', enName: 'Liucun' },
    { chName: '马骡圩', enName: 'Maluowei' },
    { chName: '兰花塘', enName: 'Lanhuatang' },
    { chName: '双垅', enName: 'Shuanglong' },
    { chName: '石碛河', enName: 'Shiqihe' },
    { chName: '桥林新城', enName: 'Qiaolinxincheng' },
    { chName: '林山', enName: 'Linshan' },
    { chName: '高家冲', enName: 'Gaojiachong' },
  ],
  'S4': [
    { chName: '滁州高铁站', enName: 'Chuzhou Railway Station' },
    { chName: '花博园', enName: 'Huaboyuan' },
    { chName: '琅琊山', enName: 'Langyashan' },
    { chName: '滁州政务中心', enName: 'Chuzhou Government Affairs Center' },
    { chName: '苏滁商务中心', enName: 'Suchu Business Center' },
    { chName: '大王郢', enName: 'Dawangying' },
    { chName: '林楼', enName: 'Linlou' },
    { chName: '十二里半', enName: 'Shierliban' },
    { chName: '汊河新城', enName: 'Chahe New Town' },
    { chName: '汊河', enName: 'Chahe' },
    { chName: '张堡', enName: 'Zhangbao' },
    { chName: '北斗产业园', enName: 'Beidouchanyeyuan' },
    { chName: '南京北站', enName: 'Nanjingbei Railway Station' },
  ],
  'S5': [
    { chName: '仙林湖', enName: 'Xianlinhu' },
    { chName: '栖霞', enName: 'Qixia' },
    { chName: '东阳街', enName: 'Dongyangjie' },
    { chName: '港城路', enName: 'Gangchenglu' },
    { chName: '花园', enName: 'Huayuan' },
    { chName: '龙潭', enName: 'Longtan' },
    { chName: '龙潭东', enName: 'Longtandong' },
    { chName: '靖安', enName: 'Jing\'an' },
    { chName: '万年路', enName: 'Wannianlu' },
    { chName: '工农路', enName: 'Gongnonglu' },
    { chName: '天宁大道', enName: 'Tianningdadao' },
    { chName: '仪征开发区', enName: 'Yizheng Development Zone' },
    { chName: '朴席', enName: 'Puxi' },
    { chName: '扬州汊河', enName: 'Yangzhouchahe' },
    { chName: '站南路', enName: 'Zhannanlu' },
    { chName: '扬州西站', enName: 'Yangzhou West Railway Station' },
  ],
  'S6': [
    { chName: '句容', enName: 'Jurong' },
    { chName: '崇明', enName: 'Chongming' },
    { chName: '华阳', enName: 'Huayang' },
    { chName: '童世界', enName: 'Tongshijie' },
    { chName: '黄梅', enName: 'Huangmei' },
    { chName: '泉都大街', enName: 'Quandudajie' },
    { chName: '汤山', enName: 'Tangshan' },
    { chName: '南京猿人洞', enName: 'Nanjingyuanrendong' },
    { chName: '古泉', enName: 'Guquan' },
    { chName: '东郊小镇', enName: 'Dongjiaoxiaozhen' },
    { chName: '麒麟门', enName: 'Qilinmen' },
    { chName: '百水桥', enName: 'Baishuiqiao' },
    { chName: '马群', enName: 'Maqun' },
  ],
  'S7': [
    { chName: '无想山', enName: 'Wuxiangshan' },
    { chName: '幸庄', enName: 'Xingzhuang' },
    { chName: '中山湖', enName: 'Zhongshanhu' },
    { chName: '溧水', enName: 'Lishui' },
    { chName: '卧龙湖', enName: 'Wolonghu' },
    { chName: '群力', enName: 'Qunli' },
    { chName: '空港新城溧水', enName: 'Konggangxinchenglishui' },
    { chName: '柘塘', enName: 'Zhetang' },
    { chName: '空港新城江宁', enName: 'Konggangxinchengjiangning' },
  ],
  'S8': [
    { chName: '金牛湖', enName: 'Jinniuhu' },
    { chName: '八百桥', enName: 'Babaiqiao' },
    { chName: '沈桥', enName: 'Shenqiao' },
    { chName: '方州广场', enName: 'Fangzhouguangchang' },
    { chName: '凤凰山公园', enName: 'Fenghuangshangongyuan' },
    { chName: '雄州', enName: 'Xiongzhou' },
    { chName: '龙池', enName: 'Longchi' },
    { chName: '六合开发区', enName: 'Luhe Development Zone' },
    { chName: '化工园', enName: 'Huagongyuan' },
    { chName: '长芦', enName: 'Changlu' },
    { chName: '葛塘', enName: 'Getang' },
    { chName: '大厂', enName: 'Dachang' },
    { chName: '卸甲甸', enName: 'Xiejiadian' },
    { chName: '信息工程大学', enName: 'NUIST' },
    { chName: '高新开发区', enName: 'Gaoxin Development Zone' },
    { chName: '泰冯路', enName: 'Taifenglu' },
    { chName: '泰山新村', enName: 'Taishanxincun' },
    { chName: '毛纺厂路', enName: 'Maofangchanglu' },
    { chName: '长江大桥北', enName: 'Changjiangdaqiaobei' },
  ],
  'S9': [
    { chName: '高淳', enName: 'Gaochun' },
    { chName: '团结圩', enName: 'Tuanjiewei' },
    { chName: '明觉', enName: 'Mingjue' },
    { chName: '石湫', enName: 'Shiqiu' },
    { chName: '铜山', enName: 'Tongshan' },
    { chName: '翔宇路南', enName: 'Xiangyulunan' },
  ],
};

export const builtinJianbanLineIds = Object.keys(builtinStationSeedsByLineId) as SupportedLineId[];
const supportedLineIds = new Set<SupportedLineId>(builtinJianbanLineIds);
const toBuiltinStationId = (lineId: SupportedLineId, index: number) => `${lineId.toLowerCase()}-jianban-${String(index + 1).padStart(2, '0')}`;

const collectTransferIdsByStationName = () => {
  const transferMap = new Map<string, Set<SupportedLineId>>();
  for (const lineId of supportedLineIds) {
    for (const station of builtinStationSeedsByLineId[lineId]) {
      if (!transferMap.has(station.chName)) {
        transferMap.set(station.chName, new Set());
      }
      transferMap.get(station.chName)?.add(lineId);
    }
  }
  return transferMap;
};

const transferIdsByStationName = collectTransferIdsByStationName();

const builtinRailwayStationChNames = new Set(['南京站', '南京南站', '南京北站', '仙林站', '句容', '姑孰', '滁州高铁站', '扬州西站', '禄口机场3号航站楼']);
const builtinAirportStationChNames = new Set(['禄口机场', '禄口机场3号航站楼']);

const builtinStationTypeFromChName = (chName: string): StationItem['type'] => {
  if (builtinAirportStationChNames.has(chName)) {
    return 'airport';
  }

  if (builtinRailwayStationChNames.has(chName)) {
    return 'railway';
  }

  return 'none';
};

export const getBuiltinJianbanStationsByLineId = (lineIdRaw: string): StationItem[] | null => {
  const lineId = lineIdRaw.trim().toUpperCase();
  if (!supportedLineIds.has(lineId as SupportedLineId)) {
    return null;
  }
  const normalizedLineId = lineId as SupportedLineId;
  return builtinStationSeedsByLineId[normalizedLineId].map((seedItem, index) => {
    const transferIds = [...(transferIdsByStationName.get(seedItem.chName) ?? [])].filter((id) => id !== normalizedLineId);
    return {
      id: toBuiltinStationId(normalizedLineId, index),
      chName: seedItem.chName,
      enName: seedItem.enName,
      type: builtinStationTypeFromChName(seedItem.chName),
      transfer: transferIds.map((id) => ({
        id,
        color: resolveJianbanLineBackgroundColor(id) ?? '#8c989f',
        textColor: resolveJianbanLineForegroundColor(id) ?? '#ffffff',
      })),
    };
  });
};
